# Generated by Django 4.2.20 on 2025-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
