# Generated by Django 4.2.20 on 2025-04-17 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_is_checked_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reader')),
            ],
        ),
    ]
