# Generated by Django 5.1.1 on 2024-09-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='books_in_bag',
            field=models.ManyToManyField(blank=True, to='api.book'),
        ),
    ]
