# Generated by Django 4.2.20 on 2025-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_checkoutrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
