# Generated by Django 5.1.1 on 2024-09-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reader_books_in_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='expected_return_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rental_date',
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_in_bag',
            field=models.ManyToManyField(blank=True, to='api.book'),
        ),
        migrations.DeleteModel(
            name='RentalRecord',
        ),
    ]
