# Generated by Django 5.1.1 on 2024-09-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_book_expected_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='books_in_bag',
        ),
    ]
