services:
  - type: web
    name: library-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn crud.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crud.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: ALLOWED_HOSTS
        value: render.com
