services:
  - type: web
    name: backend
    env: python
    buildCommand: ""
    startCommand: gunicorn crud.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crud.settings
      - key: SECRET_KEY
        value: l)(-t%4h9!t2zy#qx59+vm-zx&3)1lve&!+uv+^obx2#cbz7p
      - key: ALLOWED_HOSTS
        value: *
